name: Run Multiple R Scripts in Parallel

on:
  workflow_dispatch:
    inputs:
      num_scripts:
        description: 'Number of R scripts to run (1-100)'
        required: true
        default: '100'

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      script_matrix: ${{ steps.generate_list.outputs.matrix }}
    steps:
      - name: Generate script numbers
        id: generate_list
        run: |
          NUM_SCRIPTS=${{ github.event.inputs.num_scripts }}
          echo "Debug: Raw NUM_SCRIPTS input: $NUM_SCRIPTS"

          # Use a loop to build the array string directly without piping through multiple jqs
          # This might be more robust in some shell environments
          array_elements=""
          for i in $(seq 1 $NUM_SCRIPTS); do
            if [ -z "$array_elements" ]; then
              array_elements="$i"
            else
              array_elements="$array_elements, $i"
            fi
          done
          numbers_json="[$array_elements]"

          echo "Debug: Generated JSON string: $numbers_json"
          echo "matrix=$numbers_json" >> $GITHUB_OUTPUT

  run-r-scripts:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: ${{ fromJson(needs.generate-matrix.outputs.script_matrix) }}

    name: Run main_script${{ matrix.script }}.R
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install required R packages
        run: |
          Rscript -e 'install.packages(c("spatial", "spatstat", "igraph", "dplyr"), repos = "https://cloud.r-project.org")'

      - name: Run R script main_script${{ matrix.script }}.R
        run: Rscript main_script${{ matrix.script }}.R

      - name: List outputs for script${{ matrix.script }}
        run: |
          echo "Listing output files for script${{ matrix.script }}:"
          find outputs/script${{ matrix.script }} -type f || echo "No output files found."

      - name: Upload all output files for script${{ matrix.script }}
        uses: actions/upload-artifact@v4
        with:
          name: results-script${{ matrix.script }}
          path: outputs/script${{ matrix.script }}/
